import { Game } from "./types";

export const INITIAL_GAMES: Game[] = [
  // Hall 1 - Strategy & Expert
  {
    id: "arcs",
    title: "Arcs",
    publisher: "Leder Games",
    stall: "Stand 1-A12",
    description: "A fast-paced tactical space opera for 2 to 4 players by Cole Wehrle. Battle, scheme, and secure objective milestones throughout a dying galactic sector.",
    category: "STRATEGY",
    playerCount: "2-4",
    playTime: "60-120m",
    imageUrl: "https://cf.geekdo-images.com/zA-Vdj3enPt9mRYt94m23Q__imagepage/img/RltvScJm3bT4qmIvpZXmMBulXh4=/fit-in/900x600/filters:no_upscale():strip_icc()/pic8144052.png",
    bggLink: "https://boardgamegeek.com/boardgame/359871/arcs",
    statusText: "MUST SEE",
    hall: "Hall 1",
    mustPlay: true,
  },
  {
    id: "slay-the-spire",
    title: "Slay the Spire: The Board Game",
    publisher: "Contention Games",
    stall: "Stand 1-L02",
    description: "The official cooperative deck-building adventure board game adaptation of the mega-hit roguelike video game. Slay monsters, find relics, and craft your deck.",
    category: "EXPERT",
    playerCount: "1-4",
    playTime: "45-90m",
    imageUrl: "https://cf.geekdo-images.com/PQzVclEoOQ_wr4e1V86kxA__itemrep/img/RTxgAjHxipD5sVBYxisz2V1AruA=/fit-in/246x300/filters:strip_icc()/pic8157856.png",
    bggLink: "https://boardgamegeek.com/boardgame/338960/slay-the-spire-the-board-game",
    statusText: "LOW STOCK",
    hall: "Hall 1",
    mustPlay: true,
  },
  {
    id: "sky-team",
    title: "Sky Team",
    publisher: "Scorpion Masqué • Hachette",
    stall: "Stand 1-E12",
    description: "Cooperate with your co-pilot to land a variety of commercial airplanes in high-intensity airports worldwide. Manage speed, balance, and landing gear.",
    category: "STRATEGY",
    playerCount: "2",
    playTime: "20m",
    imageUrl: "https://cf.geekdo-images.com/uXMeQzNenHb3zK7Hoa6b2w__itemrep/img/oaw-LYEIaB20e79Y568JgyHZ5NQ=/fit-in/246x300/filters:strip_icc()/pic7398904.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/373106/sky-team",
    statusText: "DEMO READY",
    hall: "Hall 1",
    mustPlay: true,
  },
  {
    id: "forest-shuffle",
    title: "Forest Shuffle: Smoky Mountains",
    publisher: "Lookout Games • Asmodee",
    stall: "Stand 1-E18",
    description: "The long-awaited expansion for the tactical ecological card game, bringing regional balance and majestic national park environments.",
    category: "STRATEGY",
    playerCount: "2-5",
    playTime: "45-60m",
    imageUrl: "https://cf.geekdo-images.com/NFEP7jclulVFR4G5VYwgow__itemrep/img/2osXW0nI4tLGvlA9dN4k9imlEUg=/fit-in/246x300/filters:strip_icc()/pic9436525.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/463296/forest-shuffle-smoky-mountains",
    statusText: "AVAILABLE",
    hall: "Hall 1",
    mustPlay: false,
  },
  {
    id: "container",
    title: "Container",
    publisher: "Mercury Games",
    stall: "Stand 1-F04",
    description: "The classic, ruthless economic simulator of manufacturing, shipping, and tax manipulation in high-depth, player-driven markets.",
    category: "EXPERT",
    playerCount: "3-5",
    playTime: "90m",
    imageUrl: "https://cf.geekdo-images.com/dtKEFQkxDshJp4HvvI7ZlQ__imagepage/img/hyWJGTZtF8T7MGydNyL-XX8tzFk=/fit-in/900x600/filters:no_upscale():strip_icc()/pic9092338.png",
    bggLink: "https://boardgamegeek.com/boardgame/453740/container",
    statusText: "LIMITED",
    hall: "Hall 1",
    mustPlay: false,
  },
  {
    id: "drillers",
    title: "Drillers",
    publisher: "Indie Board & Cards",
    stall: "Stand 1-T10",
    description: "A deep industrial worker placement game of resource extraction, corporate development, and underground drilling.",
    category: "STRATEGY",
    playerCount: "2-4",
    playTime: "90-120m",
    imageUrl: "https://cf.geekdo-images.com/7I1Etkr46OpP-wWXVXiOKA__imagepage/img/IUjFETdTMgQM-H59vkGiO00iX_0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic9487166.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/465669/drillers",
    statusText: "DEMO READY",
    hall: "Hall 1",
    mustPlay: false,
  },
  {
    id: "yotei",
    title: "Yotei",
    publisher: "Mighty Boards",
    stall: "Stand 3-634",
    description: "Command historical clans in this elegant, beautifully illustrated area control and tile placement game situated around Mount Yotei.",
    category: "EXPERT",
    playerCount: "2-4",
    playTime: "75m",
    imageUrl: "https://cf.geekdo-images.com/5bFdfIuP0vynKpiim9mQ0g__itemrep/img/Az1Z9mkMarQzkat89PeESB_m3EA=/fit-in/246x300/filters:strip_icc()/pic9208306.png",
    bggLink: "https://boardgamegeek.com/boardgame/456860/yotei",
    statusText: "MUST SEE",
    hall: "Hall 1",
    mustPlay: false,
  },
  {
    id: "almighty",
    title: "Almighty",
    publisher: "Mantic Games",
    stall: "Stand 1-P08",
    description: "Claim deity status in this fast-paced engine building card game, engaging in mythic warfare and legendary construction.",
    category: "STRATEGY",
    playerCount: "2-4",
    playTime: "45m",
    imageUrl: "https://cf.geekdo-images.com/ZAQzUeNiRNmWJqA0uU3RCQ__imagepage/img/EhY10BI5Wqe7uy4H3-9j89All6s=/fit-in/900x600/filters:no_upscale():strip_icc()/pic9033470.png",
    bggLink: "https://boardgamegeek.com/boardgame/382158/almighty",
    statusText: "AVAILABLE",
    hall: "Hall 1",
    mustPlay: false,
  },
  {
    id: "tenby",
    title: "Tenby",
    publisher: "Surprised Stare Games",
    stall: "Stand 1-J12",
    description: "Draft cards, collect patterns, and construct colorful Welsh seaside houses in this vibrant, tactical grid builder.",
    category: "STRATEGY",
    playerCount: "1-4",
    playTime: "30-45m",
    imageUrl: "https://cf.geekdo-images.com/8L5T9-_xGX5lFF-VlU77lA__itemrep/img/975hx7-60VzXwVjo5mjkudSViUc=/fit-in/246x300/filters:strip_icc()/pic7880987.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/407233/tenby",
    statusText: "AVAILABLE",
    hall: "Hall 1",
    mustPlay: false,
  },

  // Hall 2 - Family & Social
  {
    id: "parks",
    title: "Parks",
    publisher: "Keymaster Games",
    stall: "Stand 2-C14",
    description: "Hike through gorgeous US National Parks with beautiful canvas illustrations. Gather memories, take pictures, and buy campfire equipment.",
    category: "FAMILY",
    playerCount: "1-5",
    playTime: "40-70m",
    imageUrl: "https://cf.geekdo-images.com/hHnw1JGLaEkJXaOv8bm6YQ__imagepage/img/wVbP7txcNnLBjXzeR7aFkOnC7Hg=/fit-in/900x600/filters:no_upscale():strip_icc()/pic8660069.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/437306/parks-second-edition",
    statusText: "MUST SEE",
    hall: "Hall 2",
    mustPlay: true,
  },
  {
    id: "burgle-bros-3",
    title: "Burgle Bros 3: Future Flip",
    publisher: "Fowers Games",
    stall: "Stand 2-G22",
    description: "The thrilling continuation of the cooperative heist trilogy. Bypass futuristic security, flip complex layout patterns, and escape safe zones.",
    category: "FAMILY",
    playerCount: "1-4",
    playTime: "45-60m",
    imageUrl: "https://cf.geekdo-images.com/TBx6RAAo4R5IOgXIbH8ZEA__imagepage/img/WkPniumHUdoBMQ0-yaNs12-wyi8=/fit-in/900x600/filters:no_upscale():strip_icc()/pic8562057.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/424929/burgle-bros-3-future-flip",
    statusText: "DEMO READY",
    hall: "Hall 2",
    mustPlay: false,
  },
  {
    id: "codex-naturalis",
    title: "Codex Naturalis",
    publisher: "Bombyx • Hachette",
    stall: "Stand 1-E12",
    description: "Assemble the pages of the Codex, overlapping gold-foil cards to unlock patterns, collect resources, and solve ecological grids.",
    category: "CARD GAME",
    playerCount: "2-4",
    playTime: "25m",
    imageUrl: "https://cf.geekdo-images.com/M-nflJZ6tJxNyC5CpWcJPw__imagepage/img/3L_Cxt2C24sTIDj9hOaYuGfLUzY=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6069811.png",
    bggLink: "https://boardgamegeek.com/boardgame/314503/codex-naturalis",
    statusText: "AVAILABLE",
    hall: "Hall 2",
    mustPlay: false,
  },
  {
    id: "earth-express",
    title: "Express Route",
    publisher: "Loki Kids Games",
    stall: "Stand 2-B08",
    description: "An incredibly friendly children's and family train packaging and routing game with beautiful wooden locomotive pieces.",
    category: "FAMILY",
    playerCount: "2-4",
    playTime: "30m",
    imageUrl: "https://cf.geekdo-images.com/6DdbGnmp_c1Ay5T-AmZtYA__imagepage/img/vkJZm4mdLMackDhUYU6NzpXd15Q=/fit-in/900x600/filters:no_upscale():strip_icc()/pic9498631.png",
    bggLink: "https://boardgamegeek.com/boardgame/467570/earth-express",
    statusText: "AVAILABLE",
    hall: "Hall 2",
    mustPlay: false,
  },
  {
    id: "solstis",
    title: "Solstis",
    publisher: "Lumberjacks Studio • Hachette",
    stall: "Stand 2-F02",
    description: "Light campfires and connect paths through breathtaking mountain landscapes in this quick-playing, elegant tile matchmaking game.",
    category: "FAMILY",
    playerCount: "2",
    playTime: "15-20m",
    imageUrl: "https://cf.geekdo-images.com/T6i991w8_ccgP5s2ObEIpw__itemrep/img/65R3Dtwi-isCt7cEo3pQdzLji44=/fit-in/246x300/filters:strip_icc()/pic8548331.png",
    bggLink: "https://boardgamegeek.com/boardgame/411255/solstis",
    statusText: "DEMO READY",
    hall: "Hall 2",
    mustPlay: false,
  },
  {
    id: "fetching-feathers",
    title: "Fetching Feathers",
    publisher: "Unfringed",
    stall: "Stand 2-628",
    description: "An adorable, competitive card drafting and set-collection game celebrating nature's beautiful woodland birds.",
    category: "FAMILY",
    playerCount: "2-5",
    playTime: "20m",
    imageUrl: "https://cf.geekdo-images.com/xYfCHWF-cLYLFJ6b1WMhAg__imagepage/img/pimq22AxsiLupsWlYR8Sr3MaCFE=/fit-in/900x600/filters:no_upscale():strip_icc()/pic9369001.png",
    bggLink: "https://boardgamegeek.com/boardgame/445590/peacock",
    statusText: "AVAILABLE",
    hall: "Hall 2",
    mustPlay: false,
  },
  {
    id: "flip-7",
    title: "Flip 7",
    publisher: "The Op Games",
    stall: "Stand 2-772",
    description: "A fast-paced, high-voltage press-your-luck card game where you need to accumulate high card values without drawing any duplicates.",
    category: "SOCIAL",
    playerCount: "3-8",
    playTime: "20m",
    imageUrl: "https://cf.geekdo-images.com/YrQxEB9Ef0kQorRApzG5vQ__itemrep/img/5JLNPGM983Wl2Uu2v-7JQihdFMA=/fit-in/246x300/filters:strip_icc()/pic8780246.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/420087/flip-7",
    statusText: "AVAILABLE",
    hall: "Hall 2",
    mustPlay: false,
  },
  {
    id: "stag",
    title: "Stag",
    publisher: "Bex Games",
    stall: "Stand 2-G08",
    description: "Cooperate to guide herds of noble stags through safety, using tactical hand management and gorgeous nature watercolor cards.",
    category: "SOCIAL",
    playerCount: "2-5",
    playTime: "30m",
    imageUrl: "https://cf.geekdo-images.com/dosyLCXO1803Tjxw4ogI0Q__itemrep/img/rHwyat2oOg0tgUcKV6ELmXs51BA=/fit-in/246x300/filters:strip_icc()/pic9403280.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/453777/stag",
    statusText: "AVAILABLE",
    hall: "Hall 2",
    mustPlay: false,
  },
  {
    id: "railway-porters",
    title: "Railway Porters",
    publisher: "Saashi & Saashi",
    stall: "Stand 3-761",
    description: "Manage the busy terminal as a team of railway porters, loading and organizing luggage and cargo through clever route planning.",
    category: "STRATEGY",
    imageUrl: "https://cf.geekdo-images.com/ZGmCO7QRrie9S1nMm8s83g__itemrep/img/jhsnfrWvpqYLmdRgImXI-4iGoaw=/fit-in/246x300/filters:strip_icc()/pic9575321.png",
    bggLink: "https://boardgamegeek.com/boardgame/470241/railway-porters",
    statusText: "AVAILABLE",
    hall: "Hall 2",
    mustPlay: false,
  },
  {
    id: "flip-pick-towers",
    title: "Flip Pick Towers",
    publisher: "Osprey Games",
    stall: "Stand 3A-448",
    description: "Build and flip stackable towers while racing opponents to collect matching patterns in this fast-paced dexterity puzzle game.",
    category: "FAMILY",
    imageUrl: "https://cf.geekdo-images.com/GykctngNVtwb5vjS8-1PXw__itemrep/img/FPWUGmrS11mLbufQlfMIr-Wef4Y=/fit-in/246x300/filters:strip_icc()/pic9133445.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/453283/flip-pick-towers",
    statusText: "AVAILABLE",
    hall: "Hall 2",
    mustPlay: false,
  },
  {
    id: "castle-combo",
    title: "Castle Combo",
    publisher: "La Mignonnerie",
    stall: "Stand 2-680",
    description: "A charming spatial card game where players slide and stack cards to build towers, collect treasure, and complete castle layouts.",
    category: "FAMILY",
    playerCount: "1-4",
    playTime: "20-30m",
    imageUrl: "https://cf.geekdo-images.com/rGomBfj0FGrZM-w3h5HFWQ__itemrep/img/K4E240yoCYBHiQPBQMSblVs4FUg=/fit-in/246x300/filters:strip_icc()/pic8250341.png",
    bggLink: "https://boardgamegeek.com/boardgame/416851/castle-combo",
    statusText: "AVAILABLE",
    hall: "Hall 2",
    mustPlay: false,
  },
  {
    id: "sanctuary",
    title: "Sanctuary",
    publisher: "Studio H",
    stall: "Stand 2-692",
    description: "Create a peaceful refuge by placing cards, balancing animal habitats, and unlocking tranquil sanctuary bonuses.",
    category: "CARD GAME",
    playerCount: "1-4",
    playTime: "20-30m",
    imageUrl: "https://cf.geekdo-images.com/C6V2VCtf1_7cavenn7Is3A__itemrep/img/0BtyX__4Bfd0y3dam3aqPtE3bjw=/fit-in/246x300/filters:strip_icc()/pic8932906.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/441696/sanctuary",
    statusText: "AVAILABLE",
    hall: "Hall 2",
    mustPlay: false,
  },
  {
    id: "harmonies",
    title: "Harmonies",
    publisher: "Blue Orange Games",
    stall: "Stand 2-700",
    description: "Score elegant color combinations and musical motifs in this calming tile-placement game for players who love pattern and rhythm.",
    category: "FAMILY",
    playerCount: "1-4",
    playTime: "20-30m",
    imageUrl: "https://cf.geekdo-images.com/A_XP2_VN3ugyqPhezowB_w__itemrep/img/wGng6fVAYRI5NKBX6x-pksZKJGI=/fit-in/246x300/filters:strip_icc()/pic8026369.png",
    bggLink: "https://boardgamegeek.com/boardgame/414317/harmonies",
    statusText: "AVAILABLE",
    hall: "Hall 2",
    mustPlay: false,
  },
  {
    id: "railroad-ink",
    title: "Railroad Ink: Deep Blue Edition",
    publisher: "Horrible Guild",
    stall: "Stand 2-708",
    description: "Roll dice and draw tracks to connect roads and railways in this tense roll-and-write puzzle game.",
    category: "FAMILY",
    playerCount: "1-6",
    playTime: "20m",
    imageUrl: "https://cf.geekdo-images.com/x3hjEgkxZE9M96o6wgj6Tw__itemrep/img/MpwGSYawrf0hcH-7Gc0z-lhUCvo=/fit-in/246x300/filters:strip_icc()/pic4097632.png",
    bggLink: "https://boardgamegeek.com/boardgame/245654/railroad-ink-deep-blue-edition",
    statusText: "AVAILABLE",
    hall: "Hall 2",
    mustPlay: false,
  },

  // Retail Hub - Deals
  {
    id: "ace-of-spades",
    title: "Ace of Spades",
    publisher: "Kosmos",
    stall: "Stand 3A-130",
    description: "A premium mechanical card collector and drafting board game featuring historical early aviation pilots and custom decks.",
    category: "EXCLUSIVE",
    playerCount: "2-4",
    playTime: "30m",
    imageUrl: "https://cf.geekdo-images.com/m6Do-APgKAZXZvH5UaWoCQ__imagepage/img/um2q17_-0k7i8zsCSwrUOj5lPEE=/fit-in/900x600/filters:no_upscale():strip_icc()/pic8773199.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/429861/ace-spades",
    statusText: "20% OFF TODAY",
    hall: "Retail",
    mustPlay: false,
  },
  {
    id: "in-the-ashes",
    title: "In the Ashes",
    publisher: "Iniciativa Colectiva",
    stall: "Stand R18",
    description: "A captivating dark solo scratch RPG book where your physical scratch actions permanently burn off pages to reveal items and maps.",
    category: "EXCLUSIVE",
    playerCount: "1",
    playTime: "30-60m",
    imageUrl: "https://cf.geekdo-images.com/VT00jV8ChvCZPU9QM5n5hw__itemrep/img/OB3meg479Sv8W_C90kgtdROMWZU=/fit-in/246x300/filters:strip_icc()/pic8147445.jpg",
    bggLink: "https://boardgamegeek.com/boardgame/341512/in-the-ashes",
    statusText: "LOW STOCK",
    hall: "Retail",
    mustPlay: false,
  },
];
